-- Inserir agências de estágio em Recife e região
INSERT INTO public.agencies (
  name,
  description,
  email,
  phone,
  website,
  instagram,
  address,
  city,
  state,
  cep,
  areas,
  status,
  created_by
) VALUES
  (
    'CIEE Pernambuco',
    'Centro de Integração Empresa-Escola de Pernambuco',
    'pe@ciee.org.br',
    '(81) 3421-5500',
    'https://www.ciee.org.br/portal/pe/',
    'cieepe',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'IEL - Instituto Euvaldo Lodi',
    'Instituto Euvaldo Lodi - Núcleo Regional de Pernambuco',
    'pe@iel.org.br',
    '(81) 3419-6000',
    'https://www.iel.org.br/pe',
    'ielpe',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Engenharia', 'Tecnologia', 'Administração', 'Comércio'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Nube - Núcleo Brasileiro de Estágios',
    'Núcleo Brasileiro de Estágios - Unidade Recife',
    'recife@nube.com.br',
    '(81) 3421-5500',
    'https://www.nube.com.br/',
    'nubeestagios',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Super Estágios Recife',
    'Super Estágios - Unidade Recife',
    'recife@superestagios.com.br',
    '(81) 3421-5500',
    'https://www.superestagios.com.br/',
    'superestagios',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Vagga Estágios',
    'Vagga Estágios - Unidade Recife',
    'recife@vagga.com.br',
    '(81) 3421-5500',
    'https://www.vagga.com.br/',
    'vaggaestagios',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'RHF Estágios',
    'RHF Estágios - Unidade Recife',
    'recife@rhf.com.br',
    '(81) 3421-5500',
    'https://www.rhf.com.br/',
    'rhfestagios',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Nudep - Núcleo de Desenvolvimento Profissional',
    'Núcleo de Desenvolvimento Profissional - Unidade Recife',
    'recife@nudep.com.br',
    '(81) 3421-5500',
    'https://www.nudep.com.br/',
    'nudep',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Estágio Fácil',
    'Estágio Fácil - Unidade Recife',
    'recife@estagiofacil.com.br',
    '(81) 3421-5500',
    'https://www.estagiofacil.com.br/',
    'estagiofacil',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Estágio Online',
    'Estágio Online - Unidade Recife',
    'recife@estagioonline.com.br',
    '(81) 3421-5500',
    'https://www.estagioonline.com.br/',
    'estagioonline',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Estágio Brasil',
    'Estágio Brasil - Unidade Recife',
    'recife@estagiobrasil.com.br',
    '(81) 3421-5500',
    'https://www.estagiobrasil.com.br/',
    'estagiobrasil',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Estágio Já',
    'Estágio Já - Unidade Recife',
    'recife@estagioja.com.br',
    '(81) 3421-5500',
    'https://www.estagioja.com.br/',
    'estagioja',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Estágio Legal',
    'Estágio Legal - Unidade Recife',
    'recife@estagiolegal.com.br',
    '(81) 3421-5500',
    'https://www.estagiolegal.com.br/',
    'estagiolegal',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Estágio Prime',
    'Estágio Prime - Unidade Recife',
    'recife@estagioprime.com.br',
    '(81) 3421-5500',
    'https://www.estagioprime.com.br/',
    'estagioprime',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Estágio Top',
    'Estágio Top - Unidade Recife',
    'recife@estagiotop.com.br',
    '(81) 3421-5500',
    'https://www.estagiotop.com.br/',
    'estagiotop',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ),
  (
    'Estágio Pro',
    'Estágio Pro - Unidade Recife',
    'recife@estagiopro.com.br',
    '(81) 3421-5500',
    'https://www.estagiopro.com.br/',
    'estagiopro',
    'Rua do Riachuelo, 255 - Boa Vista',
    'Recife',
    'PE',
    '50050-450',
    ARRAY['Administração', 'Comércio', 'Tecnologia', 'Saúde', 'Educação'],
    'pending',
    'ddc07fa1-3793-499d-9fc8-846577b7afb0'
  ); 