-- Objects that exist in production but were never captured in migrations.
-- Dated before 20260525 so a fresh database can run authorize() migrations.
-- On an existing project push with: supabase db push --include-all
-- Idempotent: safe to run against production (no-op for what already exists)
-- and makes a fresh database (local/staging) match the app's expectations.

-- 1. Role enums + tables used by authorize()/has_role()
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'app_role' AND typnamespace = 'public'::regnamespace) THEN
    CREATE TYPE public.app_role AS ENUM ('student', 'agency', 'admin', 'moderator');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'app_permission' AND typnamespace = 'public'::regnamespace) THEN
    CREATE TYPE public.app_permission AS ENUM ('agencies.view', 'agencies.create', 'agencies.update', 'agencies.delete', 'agencies.verify', 'agencies.review', 'resumes.view', 'resumes.analyze', 'resumes.delete', 'resumes.review', 'users.view', 'users.create', 'users.update', 'users.delete', 'users.manage_roles', 'content.view', 'content.create', 'content.update', 'content.delete', 'content.moderate', 'reports.view', 'reports.create', 'reports.resolve');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.user_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role public.app_role NOT NULL,
  UNIQUE (user_id, role)
);

CREATE TABLE IF NOT EXISTS public.role_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role public.app_role NOT NULL,
  permission text NOT NULL,
  UNIQUE (role, permission)
);

-- 2. Feedbacks (public form + admin moderation)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'feedbacks') THEN
    CREATE TABLE public.feedbacks (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
      comment text,
      email text NOT NULL,
      created_at timestamptz NOT NULL DEFAULT now()
    );

    ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;

    CREATE POLICY "Anyone can submit feedback"
      ON public.feedbacks FOR INSERT
      WITH CHECK (true);

    CREATE POLICY "Admins and moderators can view feedbacks"
      ON public.feedbacks FOR SELECT
      USING (
        EXISTS (
          SELECT 1 FROM public.user_profiles
          WHERE user_profiles.id = auth.uid()
          AND user_profiles.role IN ('admin', 'moderator')
        )
      );
  END IF;
END $$;

-- Columns written by the API (admin reply + Jotform source tracking)
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending';
ALTER TABLE public.feedbacks ADD COLUMN IF NOT EXISTS source text;
