// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptogsfpkptzpuvdluxzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0b2dzZnBrcHR6cHV2ZGx1eHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDkxMzYsImV4cCI6MjA2NTAyNTEzNn0.JxASguY2suHcxcNUwdvdQswFoUHXSWlLmsLJbRxi3A4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);